"""slay.scene.scene -- the Scene artifact: one lay arrangement, described.

Scene answers WHERE. Everything below it is local to a component or an ILS;
this is the first layer in a world frame. It takes a lay configuration --
stinger radius, roller counts, spacing, roller radii -- and produces the
arrangement those numbers describe.

WHAT SCENE DOES NOT DO, all three being boundaries that erode quietly:

  * It does not know where the PIPE is. It knows where the ROLLERS are. The
    pipe's position is a solver output, not a fact about the lay.
  * It builds no nodes and no elements. That is the model layer's work.
  * It does not sweep. It describes ONE arrangement; the sweep is the study
    layer and the per-position contact mapping is physics. There is no loop
    over shifts here and no argument named `shift`.

GLOSSARY
    extent          (s_lo, s_hi) in metres. The arc-length span of pipe the
                    model needs.
    elastic_zones   two (s_lo, s_hi) spans, one at each end of `extent`,
                    within which elements are forced fully elastic.
"""

from __future__ import annotations

from dataclasses import dataclass

import config

from slay.scene.path import LayPath
from slay.scene.rollers import (
    Station,
    StationRole,
    contact_stations,
    fixed_station,
    load_station,
    roller_stations,
)


@dataclass(frozen=True)
class Scene:
    """One lay arrangement: the path, its stations, and how much pipe it needs."""

    path: LayPath
    stations: tuple
    extent: tuple
    elastic_zones: tuple
    spacing: float

    # -- station access ---------------------------------------------------
    @property
    def contact(self) -> list:
        return contact_stations(list(self.stations))

    @property
    def fixed(self) -> Station:
        return fixed_station(list(self.stations))

    @property
    def load(self) -> Station:
        return load_station(list(self.stations))

    def by_name(self, name: str) -> Station:
        for st in self.stations:
            if st.name == name:
                return st
        raise KeyError(
            f'no station named {name!r}. Known: '
            f'{", ".join(s.name for s in self.stations)}')

    # -- zones ------------------------------------------------------------
    def in_elastic_zone(self, s: float) -> bool:
        """Whether an arc position falls in a forced-elastic end zone.

        The zones exist so that strain generated by the restraints at the
        model boundary -- an artefact of where the model was cut, not of the
        lay -- does not reach the reported results. In an elasto-plastic run
        that artefact can also drive spurious PERMANENT strain, so it does
        not wash out on unloading.

        The physics layer consumes this when binding materials. The model
        layer needs the zone boundaries as MANDATORY stations: a material
        discontinuity must not be smeared across an element, exactly as a
        section discontinuity must not.
        """
        return any(lo - 1e-12 <= s <= hi + 1e-12 for lo, hi in self.elastic_zones)

    @property
    def elastic_zone_boundaries(self) -> tuple:
        """The two interior edges of the end zones, as arc positions.

        These are the MANDATORY stations the mesher must place. The outer
        edges coincide with the model ends and are nodes anyway.
        """
        (_, lo_hi), (hi_lo, _) = self.elastic_zones
        return (lo_hi, hi_lo)


def build_scene(R: float = None,
                n_sr: int = None,
                n_vr: int = None,
                spacing: float = None,
                radii: dict = None,
                margin: float = 0.0,
                elastic_length: float = None) -> Scene:
    """Assemble a Scene from a lay configuration.

    `margin` extends the model beyond the outermost stations. It defaults to
    zero: the sweep buffer is not sized here, because the reachable-sweep
    rule is still open -- `slay_case.py` derives its ceiling from the fixed
    station sitting one spacing from the roller beside it, and that sentence
    was written when the vessel numbering ran the other way. Settling it is
    the physics layer's business, and until then a caller asks for margin
    explicitly rather than getting a guessed one.

    `elastic_length` defaults to `config.ELASTIC_END_ZONE_M`.
    """
    R = config.R_STINGER_DEF if R is None else R
    spacing = config.ROLLER_SPACING if spacing is None else spacing
    elastic_length = (config.ELASTIC_END_ZONE_M if elastic_length is None
                      else elastic_length)

    path = LayPath(R=R)
    stations = roller_stations(path, n_sr=n_sr, n_vr=n_vr, spacing=spacing,
                               radii=radii)

    if margin < 0:
        raise ValueError(f'margin must not be negative, got {margin}')

    s_lo = min(st.s_arc for st in stations) - margin
    s_hi = max(st.s_arc for st in stations) + margin
    extent = (s_lo, s_hi)

    if elastic_length < 0:
        raise ValueError(
            f'elastic end zone length must not be negative, got {elastic_length}')
    if 2 * elastic_length > (s_hi - s_lo):
        raise ValueError(
            f'elastic end zones of {elastic_length:.3f} m at each end do not '
            f'fit in a {s_hi - s_lo:.3f} m model -- they would overlap, leaving '
            f'no region where plasticity is permitted at all.')

    elastic_zones = ((s_lo, s_lo + elastic_length),
                     (s_hi - elastic_length, s_hi))

    return Scene(path=path, stations=tuple(stations), extent=extent,
                 elastic_zones=elastic_zones, spacing=spacing)
