"""slay.report.schema -- the declared contract for every result file. L8.

WHY THIS EXISTS. Before it, the CSV columns were the UNION OF WHATEVER DICTS
HAPPENED TO BE PASSED IN -- emergent from the code path, declared nowhere,
carrying no units. `envelope_strain = 0.007392` could as easily have been
read as 0.0074% as the 0.74% it is; `j1_at_pipe_moment = 1309242` gives no
hint that it is N.m; `tension_mt` is tonnes while the solver works in
newtons. Two runs a month apart could differ in their column set and nothing
would say so. That is the same class of defect as a convention held by
inspection rather than mechanically, which this project has now been bitten
by four times.

WHAT A SCHEMA HAS TO DO HERE, and it is not just a list of names:

  UNITS ARE PART OF THE COLUMN, not part of the folklore. Every field
  declares one, and `-` means genuinely dimensionless rather than unknown.

  PATTERNS ARE DECLARED, NOT ENUMERATED. A station column depends on the
  roller layout and a junction column on how many section steps a component
  has, so they cannot be listed in advance. They are declared as PATTERNS
  instead: a new junction produces a column the schema already understands,
  while a typo produces one it refuses. That is what makes an open column set
  checkable at all.

  QUANTITY AND ROLE ARE MACHINE-READABLE. A consumer -- the plotter, next --
  asks for "every strain value and its location" rather than hardcoding
  `peak_strain` and `peak_s_station`. `select()` is that query.

  EVERY PEAK CARRIES WHERE AND WHEN. A peak with no location is not a
  result, it is a number: the whole argument for sweeping is that the worst
  case is at a position you would not have picked, so a file that records the
  value without the step cannot be used to check that claim. Each peak is a
  GROUP of seven columns -- value, material position, station position,
  nearest roller, offset from it, step index, travel -- generated by
  `peak_group` so the seven can never drift apart.

VERSIONING. `SCHEMA_VERSION` changes whenever a column is added, removed or
redefined, and it is written into every file. A consumer that reads a file it
does not know the version of should say so rather than guess.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

SCHEMA_VERSION = '1.3.0'
# 1.3.0  `n_seeded`: positions that only converged via the staged seed.
#        Non-zero rows would previously have been FAILED.
# 1.2.0  the offset REGION scheme: `region_scheme`, the measured `offset_*`
#        geometry, and the patterned `x1..x5` per-region peaks. A shroud
#        steps no section, so it has no junction to probe and the region is
#        its reporting unit -- without these its case row was
#        indistinguishable from bare pipe but for `contact_lift_max`.
# 1.1.0  peak groups gained `_station` and `_station_offset`.

# Units, spelled once so they cannot drift between fields.
M = 'm'
NM = 'N.m'
MT = 'MT'
NONE = '-'          # genuinely dimensionless
IDX = 'index'
S = 's'


@dataclass(frozen=True)
class Field:
    """One column, and everything a consumer needs to use it correctly."""
    name: str
    dtype: str          # 'float' | 'int' | 'str' | 'bool'
    unit: str
    quantity: str       # 'strain' | 'moment' | 'length' | 'force' | ...
    role: str           # 'identifier' | 'input' | 'derived' | 'value' |
                        # 'location' | 'step' | 'status'
    about: str
    pattern: bool = False
    per: str = 'case'   # the GRAIN the value belongs to: 'case' (constant
                        # through the file), 'position' (constant within one
                        # passage step), 'sample' (varies row to row). A
                        # long-format file is only checkable if the grain is
                        # declared -- `profile.write` asserts every 'case'
                        # column is in fact constant, which is how a writer
                        # that leaks a per-row value into a case column is
                        # caught by the file rather than by a reader's eye.

    @property
    def rx(self):
        return re.compile(self.name if self.pattern else re.escape(self.name))


def peak_group(prefix: str, quantity: str, unit: str, what: str) -> list:
    """The seven columns that make one peak QUERYABLE.

    A value with no location and no step is not a result. The whole argument
    for sweeping a component past a roller is that the worst case falls at a
    position nobody would have picked in advance -- so a file that records
    the number without the step cannot be used to check that, or to find the
    case again, or to plot it.

    Generated rather than written out four times, so the seven cannot drift
    apart as they would if each peak spelled its own.
    """
    return [
        Field(f'{prefix}', 'float', unit, quantity, 'value',
              f'{what}, worst over the whole passage'),
        Field(f'{prefix}_s_material', 'float', M, 'length', 'location',
              f'material coordinate of {what} -- labels a point on the PIPE '
              f'and travels with it'),
        Field(f'{prefix}_s_station', 'float', M, 'length', 'location',
              f'station coordinate of {what} -- where on the STINGER, and '
              f'the coordinate to compare across positions'),
        Field(f'{prefix}_station', 'str', NONE, 'name', 'location',
              f'nearest roller to {what}'),
        Field(f'{prefix}_station_offset', 'float', M, 'length', 'location',
              f'signed distance from that roller, + toward the stinger'),
        Field(f'{prefix}_step', 'int', IDX, 'count', 'step',
              f'passage position index at which {what} occurred'),
        Field(f'{prefix}_shift', 'float', M, 'length', 'step',
              f'travel along the passage at that position'),
    ]


# ---------------------------------------------------------------------------
# the fixed columns
# ---------------------------------------------------------------------------

IDENTITY = [
    Field('schema_version', 'str', NONE, 'name', 'identifier',
          'version of THIS contract; a reader that does not know it should '
          'say so rather than guess'),
    Field('case_id', 'str', NONE, 'name', 'identifier', 'unique per case'),
    Field('family', 'str', NONE, 'name', 'identifier',
          "'plain' or the component archetype"),
    Field('design', 'str', NONE, 'name', 'identifier',
          "'ofat' (one axis varied from the baseline) or 'lhs' (joint "
          "sample); the two answer different questions and must not be "
          "pooled without saying so"),
    Field('git_sha', 'str', NONE, 'name', 'identifier',
          'commit the run was produced at'),
    Field('produced_at', 'str', NONE, 'name', 'identifier',
          'UTC timestamp, ISO 8601'),
]

INPUTS = [
    Field('R', 'float', M, 'length', 'input',
          'stinger radius, to the ROLLER CENTRELINE'),
    Field('spacing', 'float', M, 'length', 'input', 'roller spacing'),
    Field('OD', 'float', M, 'length', 'input', 'pipeline outside diameter'),
    Field('t_wall', 'float', M, 'length', 'input', 'pipeline wall thickness'),
    Field('tension_mt', 'float', MT, 'force', 'input',
          'lay tension in METRIC TONNES; the solver works in newtons '
          '(x 9806.65)'),
    Field('L_comp', 'float', M, 'length', 'input',
          'component length; 0 for plain pipe'),
    Field('L_OD', 'float', NONE, 'ratio', 'input',
          'component length in pipe diameters'),
    Field('t_ratio', 'float', NONE, 'ratio', 'input',
          'component wall over pipe wall'),
    Field('contact_surface', 'str', NONE, 'name', 'input',
          "'centreline' (pipe centreline driven onto the R arc) or 'bottom' "
          "(R + r_roller + OD/2); they differ by about 1%"),
    Field('mode', 'str', NONE, 'name', 'input',
          "'A' carries state between positions (the real path, and the only "
          "mode that accumulates plasticity); 'B' solves each from virgin"),
    Field('material', 'str', NONE, 'name', 'input',
          "'j2', 'ro' or 'elastic'"),
    Field('step', 'float', M, 'length', 'input',
          'sweep step: the travel between sampled positions. Edge crossings '
          'are solved regardless of it, so the envelope does not depend on '
          'it (a whole-element step alone was 16% low)'),
]

DERIVED = [
    Field('stiffness_ratio', 'float', NONE, 'ratio', 'derived',
          'component second moment over pipeline second moment, off the '
          'SOLVED sections; 1.0 when nothing steps'),
    Field('contact_lift_max', 'float', M, 'length', 'derived',
          'deepest CENTRELINE LIFT the component applies above the '
          'plain-pipe baseline. FOR A SHROUD THIS IS THE ENTIRE COMPONENT: '
          'GD-SH adds no bending stiffness, so without this column its case '
          'is indistinguishable from bare pipe. Measured 0.20320 m for '
          'GD-SH (= V - OD/2), 0.04400 for GD-TT, 0.02100 for GD-TP'),
    Field('contact_lift_station', 'str', NONE, 'name', 'location',
          'roller under the deepest lift, over the whole passage'),
    Field('contact_lift_step', 'int', IDX, 'count', 'step',
          'position index at which that lift was reached. At the LEADING '
          'EDGE of a tapered component the lift is correctly ZERO, so a '
          'single position proves nothing'),
    Field('comp_s_lead', 'float', M, 'length', 'location',
          "component LEADING (stinger-side) edge in STATION coordinates, at "
          "the envelope position. Without it a reader has the component's "
          "length but not where it was"),
    Field('comp_s_trail', 'float', M, 'length', 'location',
          'component TRAILING (vessel-side) edge, station coordinates, at '
          'the envelope position'),
    Field('junction_snapshot_step', 'int', IDX, 'count', 'step',
          'position index the junction SNAPSHOT columns were taken at (the '
          'bare `j*` names; the `_env` ones are over all positions)'),
    Field('junction_snapshot_shift', 'float', M, 'length', 'step',
          'travel at that position'),
    Field('n_junctions', 'int', NONE, 'count', 'derived',
          'section steps in the model; 0 for plain pipe and for a component '
          'that shares the pipe section'),
    Field('n_positions', 'int', NONE, 'count', 'derived',
          'positions the passage scheduled'),
    Field('n_converged', 'int', NONE, 'count', 'derived',
          'positions that converged'),
    Field('n_seeded', 'int', NONE, 'count', 'derived',
          'positions that only converged via the STAGED SEED -- bend the '
          'pipe onto the rollers elastically, then add gravity, then '
          'tension, then chain the real solve onto that. Seeding is a '
          'FALLBACK: a position that converges directly never uses it and '
          'keeps its exact load path, so this column is 0 for almost every '
          'case. Where it is not 0 the case would otherwise have been '
          'FAILED, and the row is telling you the answer came by a '
          'different route'),
    Field('zone_s_max', 'float', M, 'length', 'derived',
          'reporting band cut, in STATION coordinates; everything at or '
          'beyond it is excluded (the D6 tip artefact)'),
    Field('zone_label', 'str', NONE, 'name', 'derived',
          'which stations the band drops'),
    Field('start_strain', 'float', NONE, 'strain', 'value',
          'peak strain at the START position -- what a single-position solve '
          'would have reported'),

    # ---- offset (shroud) geometry ----------------------------------------
    #
    # MEASURED off the solved contact profile, not copied from the archetype
    # definition, so these describe the component that was solved rather than
    # the one that was asked for.
    Field('region_scheme', 'str', NONE, 'name', 'derived',
          "which region scheme the `x*` columns follow, or empty when the "
          "case has none. 'X1-X5/offset' is the five-region scheme for an "
          'offset body: taper+beyond, then the deep section in thirds from '
          'the catenary side, then taper+beyond'),
    Field('offset_L1', 'float', M, 'length', 'derived',
          'DEEP SECTION length of the offset body -- the part at full depth. '
          'X2/X3/X4 are its thirds'),
    Field('offset_L2', 'float', M, 'length', 'derived',
          'taper length, mean of the two ends'),
    Field('offset_L2_cat', 'float', M, 'length', 'derived',
          'taper length on the CATENARY side (high s)'),
    Field('offset_L2_ves', 'float', M, 'length', 'derived',
          'taper length on the VESSEL side (low s). Differs from '
          '`offset_L2_cat` only for an asymmetric body'),
    Field('offset_V', 'float', M, 'length', 'derived',
          'offset depth below the pipe CENTRELINE. The pipe is held off the '
          'rollers by V - OD/2, NOT by V -- using V over-elevates by half a '
          'diameter (33% too much at V = 2D)'),
    Field('offset_owner', 'str', NONE, 'name', 'derived',
          'the component that owns the offset, e.g. GD-SH'),
]

PEAKS = (
    peak_group('peak_strain', 'strain', NONE,
               'peak extreme-fibre strain in the reporting band (a FRACTION: '
               '0.0074 is 0.74%)')
    + peak_group('peak_moment', 'moment', NM,
                 'peak bending moment magnitude in the reporting band')
    + peak_group('body_peak_strain', 'strain', NONE,
                 'peak strain ON THE COMPONENT BODY')
    + peak_group('body_peak_moment', 'moment', NM,
                 'peak bending moment magnitude on the component body')
)

STATUS = [
    Field('status', 'str', NONE, 'name', 'status',
          "'ok', 'partial n/m', or 'FAILED'; a case that did not fully "
          'converge is RECORDED, never dropped'),
    Field('error', 'str', NONE, 'name', 'status', 'reason, when it failed'),
    Field('seconds', 'float', S, 'time', 'status', 'wall-clock solve time'),
    Field('n_active', 'int', NONE, 'count', 'status',
          'contact slots active at the envelope position'),
    Field('n_slots', 'int', NONE, 'count', 'status', 'contact slots in all'),
]

FIXED = IDENTITY + INPUTS + DERIVED + PEAKS + STATUS

# ---------------------------------------------------------------------------
# the patterned columns -- open sets, declared rather than enumerated
# ---------------------------------------------------------------------------

PATTERNS = [
    Field(r's_[A-Za-z]+\d*', 'float', M, 'length', 'location',
          'ARC POSITION of that station along the stinger. Without these a '
          'consumer has `eps_SR2_env` but no way to place SR2, and deriving '
          'it from `spacing` assumes a layout the file never states',
          pattern=True),
    Field(r'eps_[A-Za-z]+\d*_env', 'float', NONE, 'strain', 'value',
          'worst strain at that station over the whole passage (MAX over '
          'positions, never a sum)', pattern=True),
    Field(r'j\d+_at_(pipe|component|na)_strain(_env)?', 'float', NONE,
          'strain', 'value',
          'strain at a junction, on the named side; bare name is the '
          'SNAPSHOT at the envelope position, `_env` the worst at any '
          'position', pattern=True),
    Field(r'j\d+_at_(pipe|component|na)_moment(_env)?', 'float', NM,
          'moment', 'value', 'bending moment at a junction, on the named '
          'side', pattern=True),
    Field(r'j\d+_at_(pipe|component|na)_s', 'float', M, 'length', 'location',
          'material coordinate of that junction probe', pattern=True),
    Field(r'j\d+_at_(pipe|component|na)_clamped', 'bool', NONE, 'flag',
          'status',
          'the section run ended before the requested point, so this is the '
          'nearest available datum rather than the requested one',
          pattern=True),
    Field(r'j\d+_[mp]\d+(\.\d+)?OD_strain(_env)?', 'float', NONE, 'strain',
          'value',
          'strain at an offset from a junction, in pipe diameters; `m` is '
          'toward the vessel, `p` toward the stinger', pattern=True),
    Field(r'j\d+_[mp]\d+(\.\d+)?OD_moment(_env)?', 'float', NM, 'moment',
          'value', 'bending moment at an offset from a junction',
          pattern=True),
    Field(r'j\d+_[mp]\d+(\.\d+)?OD_s', 'float', M, 'length', 'location',
          'material coordinate of that offset probe', pattern=True),
    Field(r'j\d+_[mp]\d+(\.\d+)?OD_clamped', 'bool', NONE, 'flag', 'status',
          'clamped to the nearest available datum', pattern=True),
    Field(r'j\d+_(at_(pipe|component|na)|[mp]\d+(\.\d+)?OD)_side', 'str',
          NONE, 'name', 'location',
          "which BODY the probe landed in -- 'pipe' or 'component'. Without "
          'it a consumer cannot tell which side of a section step a probe '
          'is on, and a profile drawn from the file connects points across '
          'a discontinuity that strain genuinely has', pattern=True),
    Field(r'j\d+_(at_(pipe|component|na)|[mp]\d+(\.\d+)?OD)_owner', 'str',
          NONE, 'name', 'location',
          'the component that owns the surface there, or `pipe`',
          pattern=True),

    # ---- the offset (shroud) REGION scheme -------------------------------
    #
    # Patterned for the same reason the junction columns are: they exist only
    # for a case that HAS an offset body, and how many there are depends on
    # the scheme rather than on anything fixed here. A shroud has no junction
    # to probe -- it steps no section -- so the region is its reporting unit.
    Field(r'x\d_peak_strain', 'float', NONE, 'strain', 'value',
          'worst strain in that region over the WHOLE passage (MAX over '
          'positions, never a sum). X2, the catenary-side third of the deep '
          'section, is the peak in every case measured and is the region '
          'that governs design', pattern=True),
    Field(r'x\d_peak_strain_s_material', 'float', M, 'length', 'location',
          'material coordinate of that peak -- a point on the PIPE, which '
          'travels with it', pattern=True),
    Field(r'x\d_peak_strain_s_station', 'float', M, 'length', 'location',
          'station coordinate of that peak at the step it occurred',
          pattern=True),
    Field(r'x\d_peak_strain_step', 'int', IDX, 'count', 'step',
          'passage position index at which the region peaked; -1 if the '
          'region never had an element inside the reporting band',
          pattern=True),
    Field(r'x\d_peak_strain_shift', 'float', M, 'length', 'step',
          'travel at that position', pattern=True),
    Field(r'x\d_peak_moment', 'float', NM, 'moment', 'value',
          'worst bending moment magnitude in that region over the passage',
          pattern=True),
    Field(r'x\d_frac_of_x2', 'float', NONE, 'ratio', 'derived',
          'the region peak over X2. The reference puts X3 at 0.65-0.75 and '
          'X4 lower still, so this is the column that says whether a case '
          'behaves like the published scheme', pattern=True),
    Field(r'x\d_peak_on_shroud', 'bool', NONE, 'flag', 'location',
          'the region peak landed within the shroud footprint. X1 and X5 '
          'each lump a TAPER together with the plain pipe beyond it, and the '
          'reference calls both "governed by the plain-pipe catenary" -- '
          'true at its own 2xOD mesh, false when refined, where the peak '
          'migrates onto the catenary-side taper. Without this column a '
          'reader cannot tell which of the two an X1 peak happened on',
          pattern=True),
    Field(r'x\d_s_lo', 'float', M, 'length', 'location',
          'region lower bound in MATERIAL coordinates -- fixed on the steel, '
          'so it names the same pipe at every position. EMPTY where the '
          'region is unbounded (X5 runs back toward the vessel)',
          pattern=True),
    Field(r'x\d_s_hi', 'float', M, 'length', 'location',
          'region upper bound, material coordinates. EMPTY where unbounded '
          '(X1 runs out toward the stinger tip)', pattern=True),
    Field(r'x\d_n_elements', 'int', NONE, 'count', 'derived',
          'elements the region contains. A region with one or two elements '
          'is reporting a mesh, not a strain field', pattern=True),
]


# ---------------------------------------------------------------------------
# queries
# ---------------------------------------------------------------------------

_BY_NAME = {f.name: f for f in FIXED}


def describe(column: str):
    """The `Field` for a column name, fixed or patterned. None if unknown."""
    f = _BY_NAME.get(column)
    if f is not None:
        return f
    for p in PATTERNS:
        if re.fullmatch(p.name, column):
            return p
    return None


def unknown(columns) -> list:
    """Columns this contract does not describe, in order.

    THE POINT OF THE WHOLE MODULE. An open column set is still checkable so
    long as the openness is declared: a new junction matches a pattern and
    passes, a misspelt one matches nothing and is refused.
    """
    return [c for c in columns if describe(c) is None]


def select(quantity: str = None, role: str = None, unit: str = None) -> list:
    """Fixed fields matching all the given criteria.

    What a consumer asks instead of hardcoding column names -- "every strain
    value", "every location" -- so that adding a peak does not require
    editing the plotter.
    """
    out = []
    for f in FIXED:
        if quantity is not None and f.quantity != quantity:
            continue
        if role is not None and f.role != role:
            continue
        if unit is not None and f.unit != unit:
            continue
        out.append(f)
    return out


def peak_names() -> list:
    """The prefix of every peak group, e.g. 'peak_strain'.

    A peak is a group of seven columns and this is how a consumer finds the
    groups without knowing how many there are.
    """
    return [f.name for f in FIXED
            if f.role == 'value' and f'{f.name}_step' in _BY_NAME]


def group(prefix: str) -> dict:
    """{role-ish key: column name} for one peak group.

    Lets a caller write `g['value']`, `g['s_station']`, `g['step']` rather
    than rebuilding the suffixes.
    """
    if f'{prefix}_step' not in _BY_NAME:
        raise KeyError(f'{prefix!r} is not a peak group; have {peak_names()}')
    keys = ('s_material', 's_station', 'station', 'station_offset', 'step',
            'shift')
    out = {'value': prefix}
    out.update({k: f'{prefix}_{k}' for k in keys})
    return out


def header() -> list:
    """Every fixed column, in declared order. Patterned ones append after."""
    return [f.name for f in FIXED]


def as_dict() -> dict:
    """The whole contract, serialisable -- written beside every result file
    so a reader never has to have this source to interpret one."""
    def row(f):
        return dict(name=f.name, dtype=f.dtype, unit=f.unit,
                    quantity=f.quantity, role=f.role, about=f.about,
                    pattern=f.pattern, per=f.per)
    return dict(schema_version=SCHEMA_VERSION,
                fields=[row(f) for f in FIXED],
                patterns=[row(f) for f in PATTERNS])
